In [1]:
import numpy as np
import pandas as pd

In [4]:
customers = pd.read_csv("customers.csv")

In [5]:
customers = pd.read_csv("customers.csv")

In [6]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
sellers = pd.read_csv("sellers.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

In [7]:
customers.shape
products.shape
sellers.shape
orders.shape
order_items.shape

(105953, 9)

In [8]:
customers = pd.read_csv("customers.csv")

In [9]:
customers.shape

(2000, 9)

In [10]:
products = pd.read_csv("products.csv")

In [11]:
products.shape

(420, 7)

In [12]:
order_items = pd.read_csv("order_items.csv")

In [13]:
order_items.shape

(105953, 9)

In [14]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       2000 non-null   str
 1   Customer_Name     2000 non-null   str
 2   Gender            2000 non-null   str
 3   Age               2000 non-null   int64
 4   Customer_Segment  2000 non-null   str
 5   City              2000 non-null   str
 6   State             2000 non-null   str
 7   Region            2000 non-null   str
 8   Signup_Date       2000 non-null   str
dtypes: int64(1), str(8)
memory usage: 140.8 KB

In [15]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    420 non-null    str
 1   Product_Name  420 non-null    str
 2   Category      420 non-null    str
 3   Subcategory   420 non-null    str
 4   Brand         420 non-null    str
 5   Unit_Cost     420 non-null    float64
 6   Unit_Price    420 non-null    int64
dtypes: float64(1), int64(1), str(5)
memory usage: 23.1 KB

In [16]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Seller_ID      100 non-null    str
 1   Seller_Name    100 non-null    str
 2   Seller_Type    100 non-null    str
 3   Seller_Region  100 non-null    str
dtypes: str(4)
memory usage: 3.3 KB

In [17]:
customers.isnull().sum()

Customer_ID         0
Customer_Name       0
Gender              0
Age                 0
Customer_Segment    0
City                0
State               0
Region              0
Signup_Date         0
dtype: int64

In [18]:
sellers.isnull().sum()

Seller_ID        0
Seller_Name      0
Seller_Type      0
Seller_Region    0
dtype: int64

In [19]:
products.isnull().sum()

Product_ID      0
Product_Name    0
Category        0
Subcategory     0
Brand           0
Unit_Cost       0
Unit_Price      0
dtype: int64

In [20]:
order_items.isnull().sum()

Order_ID        0
Product_ID      0
Seller_ID       0
Quantity        0
Discount        0
Sales           0
Cost            0
Profit          0
Order_Status    0
dtype: int64

In [21]:
orders.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Seller_ID         0
Order_Status      0
Payment_Method    0
Shipping_Mode     0
dtype: int64

In [22]:
customers.duplicated().sum()

np.int64(0)

In [23]:
orders.duplicated().sum()

np.int64(0)

In [24]:
order_itmes.duplicates().sum()
sellers.duplicated().sum()

NameError: name 'order_itmes' is not defined

In [25]:
order_items.duplicates().sum()
sellers.duplicated().sum()

AttributeError: 'DataFrame' object has no attribute 'duplicates'

In [27]:
order_items.duplicated().sum()
sellers.duplicated().sum()

np.int64(0)

In [28]:
customers.describe()

              Age
count  2000.00000
mean     43.48100
std      14.76952
min      18.00000
25%      31.00000
50%      44.00000
75%      56.00000
max      68.00000

In [29]:
sellers.describe()

       Seller_ID Seller_Name Seller_Type Seller_Region
count        100         100         100           100
unique       100         100           3             4
top        S0001  Seller 001     Premium          East
freq           1           1          41            29

In [30]:
orders.describe()

,Order_ID,Order_Date,Customer_ID,Seller_ID,Order_Status,Payment_Method,Shipping_Mode
count,50000,50000,50000,50000,50000,50000,50000
unique,50000,956,2000,100,4,6,3
top,O0000001,2026-05-16,C01007,S0048,Completed,Wallet,Same Day
freq,1,77,44,553,42954,8542,16830

In [31]:
products.describe()

          Unit_Cost    Unit_Price
count    420.000000    420.000000
mean    5541.953500   8940.952381
std     9195.021243  14677.124540
min        0.000000      0.000000
25%      724.042500   1200.000000
50%     2124.530000   3400.000000
75%     4927.100000   8075.000000
max    64646.390000  89800.000000

In [32]:
order_items.describe()

,Quantity,Discount,Sales,Cost,Profit
count,105953.000000,105953.000000,105953.000000,105953.000000,105953.000000
mean,2.498400,0.110989,19888.957122,13895.131151,5993.825971
std,1.117983,0.077258,36917.744589,25992.169875,12486.239649
min,1.000000,0.000000,0.000000,0.000000,-23105.560000
25%,1.000000,0.050000,2375.000000,1642.580000,599.010000
50%,3.000000,0.100000,6402.000000,4528.050000,1736.490000
75%,3.000000,0.150000,18624.000000,12986.760000,5444.760000
max,4.000000,0.300000,359200.000000,258585.560000,175884.360000

In [33]:
products.duplicated().sum()

np.int64(0)

In [34]:
sellers.shape
sellers.info()
sellers.duplicated().sum()
sellers.isnull().sum()
sellers.describe()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Seller_ID      100 non-null    str
 1   Seller_Name    100 non-null    str
 2   Seller_Type    100 non-null    str
 3   Seller_Region  100 non-null    str
dtypes: str(4)
memory usage: 3.3 KB

       Seller_ID Seller_Name Seller_Type Seller_Region
count        100         100         100           100
unique       100         100           3             4
top        S0001  Seller 001     Premium          East
freq           1           1          41            29

In [35]:
sellers.shape

(100, 4)

In [36]:
sellers.duplicated().sum()

np.int64(0)

In [37]:
sellers.isnull().sum()

Seller_ID        0
Seller_Name      0
Seller_Type      0
Seller_Region    0
dtype: int64

In [38]:
sellers.shape,
sellers.info(),
sellers.duplicated().sum(),
sellers.isnull().sum(),
sellers.describe()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Seller_ID      100 non-null    str
 1   Seller_Name    100 non-null    str
 2   Seller_Type    100 non-null    str
 3   Seller_Region  100 non-null    str
dtypes: str(4)
memory usage: 3.3 KB

       Seller_ID Seller_Name Seller_Type Seller_Region
count        100         100         100           100
unique       100         100           3             4
top        S0001  Seller 001     Premium          East
freq           1           1          41            29

In [39]:
sellers.shape()

TypeError: 'tuple' object is not callable

In [40]:
orders.shape

(50000, 7)

In [41]:
orders.duplicated().sum()

np.int64(0)

In [42]:
orders.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Seller_ID         0
Order_Status      0
Payment_Method    0
Shipping_Mode     0
dtype: int64

In [43]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50000 non-null  str
 1   Order_Date      50000 non-null  str
 2   Customer_ID     50000 non-null  str
 3   Seller_ID       50000 non-null  str
 4   Order_Status    50000 non-null  str
 5   Payment_Method  50000 non-null  str
 6   Shipping_Mode   50000 non-null  str
dtypes: str(7)
memory usage: 2.7 MB

In [44]:
orders.describe()

,Order_ID,Order_Date,Customer_ID,Seller_ID,Order_Status,Payment_Method,Shipping_Mode
count,50000,50000,50000,50000,50000,50000,50000
unique,50000,956,2000,100,4,6,3
top,O0000001,2026-05-16,C01007,S0048,Completed,Wallet,Same Day
freq,1,77,44,553,42954,8542,16830

In [45]:
order_items.shape
order_items.info()
order_items.duplicated().sum()
order_items.isnull().sum()
order_items.describe()

<class 'pandas.DataFrame'>
RangeIndex: 105953 entries, 0 to 105952
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Order_ID      105953 non-null  str
 1   Product_ID    105953 non-null  str
 2   Seller_ID     105953 non-null  str
 3   Quantity      105953 non-null  int64
 4   Discount      105953 non-null  float64
 5   Sales         105953 non-null  float64
 6   Cost          105953 non-null  float64
 7   Profit        105953 non-null  float64
 8   Order_Status  105953 non-null  str
dtypes: float64(4), int64(1), str(4)
memory usage: 7.3 MB

,Quantity,Discount,Sales,Cost,Profit
count,105953.000000,105953.000000,105953.000000,105953.000000,105953.000000
mean,2.498400,0.110989,19888.957122,13895.131151,5993.825971
std,1.117983,0.077258,36917.744589,25992.169875,12486.239649
min,1.000000,0.000000,0.000000,0.000000,-23105.560000
25%,1.000000,0.050000,2375.000000,1642.580000,599.010000
50%,3.000000,0.100000,6402.000000,4528.050000,1736.490000
75%,3.000000,0.150000,18624.000000,12986.760000,5444.760000
max,4.000000,0.300000,359200.000000,258585.560000,175884.360000

In [46]:
order_items.shape

(105953, 9)

In [48]:
order_items.duplicated().sum()

np.int64(0)

In [49]:
order_items.isnull().sum()

Order_ID        0
Product_ID      0
Seller_ID       0
Quantity        0
Discount        0
Sales           0
Cost            0
Profit          0
Order_Status    0
dtype: int64

In [50]:
products.describe()
order_items.describe()

,Quantity,Discount,Sales,Cost,Profit
count,105953.000000,105953.000000,105953.000000,105953.000000,105953.000000
mean,2.498400,0.110989,19888.957122,13895.131151,5993.825971
std,1.117983,0.077258,36917.744589,25992.169875,12486.239649
min,1.000000,0.000000,0.000000,0.000000,-23105.560000
25%,1.000000,0.050000,2375.000000,1642.580000,599.010000
50%,3.000000,0.100000,6402.000000,4528.050000,1736.490000
75%,3.000000,0.150000,18624.000000,12986.760000,5444.760000
max,4.000000,0.300000,359200.000000,258585.560000,175884.360000

In [51]:
products.describe()

          Unit_Cost    Unit_Price
count    420.000000    420.000000
mean    5541.953500   8940.952381
std     9195.021243  14677.124540
min        0.000000      0.000000
25%      724.042500   1200.000000
50%     2124.530000   3400.000000
75%     4927.100000   8075.000000
max    64646.390000  89800.000000

In [52]:
order_items.describe()

,Quantity,Discount,Sales,Cost,Profit
count,105953.000000,105953.000000,105953.000000,105953.000000,105953.000000
mean,2.498400,0.110989,19888.957122,13895.131151,5993.825971
std,1.117983,0.077258,36917.744589,25992.169875,12486.239649
min,1.000000,0.000000,0.000000,0.000000,-23105.560000
25%,1.000000,0.050000,2375.000000,1642.580000,599.010000
50%,3.000000,0.100000,6402.000000,4528.050000,1736.490000
75%,3.000000,0.150000,18624.000000,12986.760000,5444.760000
max,4.000000,0.300000,359200.000000,258585.560000,175884.360000

In [53]:
products[products["Unit_Cost"]==0]

,Product_ID,Product_Name,Category,Subcategory,Brand,Unit_Cost,Unit_Price
345,P0346,PrimeLine Writing 01,Office Supplies,Writing,PrimeLine,0.0,0

In [54]:
products[products["Unit_Price"]==0]

,Product_ID,Product_Name,Category,Subcategory,Brand,Unit_Cost,Unit_Price
345,P0346,PrimeLine Writing 01,Office Supplies,Writing,PrimeLine,0.0,0

In [56]:
products[products["Unit_Cost"]>products["Unit_Price"]]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Subcategory, Brand, Unit_Cost, Unit_Price]
Index: []

In [58]:
order_items[order_items["Sales"]==0]

,Order_ID,Product_ID,Seller_ID,Quantity,Discount,Sales,Cost,Profit,Order_Status
890,O0000415,P0346,S0063,1,0.08,0.0,0.0,0.0,Completed
1181,O0000547,P0346,S0027,2,0.00,0.0,0.0,0.0,Completed
1362,O0000627,P0346,S0085,2,0.05,0.0,0.0,0.0,Completed
1501,O0000696,P0346,S0096,2,0.15,0.0,0.0,0.0,Completed
1857,O0000857,P0346,S0074,4,0.25,0.0,0.0,0.0,Completed
...,...,...,...,...,...,...,...,...,...
104259,O0049211,P0346,S0044,1,0.12,0.0,0.0,0.0,Completed
104472,O0049316,P0346,S0051,3,0.00,0.0,0.0,0.0,Completed
104500,O0049328,P0346,S0029,4,0.05,0.0,0.0,0.0,Completed
104504,O0049330,P0346,S0080,1,0.10,0.0,0.0,0.0,Completed
105364,O0049734,P0346,S0005,4,0.12,0.0,0.0,0.0,Completed

In [60]:
order_items[order_items["Cost"]==0]

,Order_ID,Product_ID,Seller_ID,Quantity,Discount,Sales,Cost,Profit,Order_Status
890,O0000415,P0346,S0063,1,0.08,0.0,0.0,0.0,Completed
1181,O0000547,P0346,S0027,2,0.00,0.0,0.0,0.0,Completed
1362,O0000627,P0346,S0085,2,0.05,0.0,0.0,0.0,Completed
1501,O0000696,P0346,S0096,2,0.15,0.0,0.0,0.0,Completed
1857,O0000857,P0346,S0074,4,0.25,0.0,0.0,0.0,Completed
...,...,...,...,...,...,...,...,...,...
104259,O0049211,P0346,S0044,1,0.12,0.0,0.0,0.0,Completed
104472,O0049316,P0346,S0051,3,0.00,0.0,0.0,0.0,Completed
104500,O0049328,P0346,S0029,4,0.05,0.0,0.0,0.0,Completed
104504,O0049330,P0346,S0080,1,0.10,0.0,0.0,0.0,Completed
105364,O0049734,P0346,S0005,4,0.12,0.0,0.0,0.0,Completed

In [62]:
order_items[order_items["Profit"]<0]

,Order_ID,Product_ID,Seller_ID,Quantity,Discount,Sales,Cost,Profit,Order_Status
244,O0000114,P0120,S0066,4,0.25,23400.0,24080.16,-680.16,Completed
467,O0000218,P0309,S0093,1,0.25,825.0,837.35,-12.35,Completed
559,O0000260,P0312,S0080,2,0.25,1800.0,1833.20,-33.20,Completed
710,O0000329,P0153,S0075,2,0.25,8850.0,8898.30,-48.30,Completed
834,O0000384,P0004,S0093,4,0.25,187800.0,193043.32,-5243.32,Completed
...,...,...,...,...,...,...,...,...,...
105284,O0049696,P0153,S0095,1,0.25,4425.0,4449.15,-24.15,Completed
105461,O0049777,P0223,S0013,4,0.25,900.0,921.32,-21.32,Returned
105701,O0049883,P0124,S0030,1,0.25,2475.0,2476.78,-1.78,Completed
105750,O0049906,P0040,S0056,2,0.25,12600.0,12986.76,-386.76,Completed
105945,O0049997,P0004,S0043,2,0.30,87640.0,96521.66,-8881.66,Completed

In [64]:
order_items[order_items["Sales"] == 0]["Order_Status"].value_counts()

Order_Status
Completed    214
Returned      14
Cancelled     12
Pending        6
Name: count, dtype: int64

In [65]:
products_clean = products.copy()

In [66]:
products_clean = orders.copy()

In [67]:
order_items_clean = order_items.copy()

In [68]:
orders_clean = orders.copy()

In [69]:
customers_clean = customers.copy()

In [70]:
sellers_clean = sellers.copy()

In [77]:
products_clean.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Seller_ID', 'Order_Status',
       'Payment_Method', 'Shipping_Mode'],
      dtype='str')

In [78]:
products_clean.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_ID',
 'Seller_ID',
 'Order_Status',
 'Payment_Method',
 'Shipping_Mode']

In [79]:
products_clean = products.copy()

In [80]:
products_clean.columns.tolist()

['Product_ID',
 'Product_Name',
 'Category',
 'Subcategory',
 'Brand',
 'Unit_Cost',
 'Unit_Price']

In [81]:
products_clean[products_clean["Product_ID"] == "P0346"]

,Product_ID,Product_Name,Category,Subcategory,Brand,Unit_Cost,Unit_Price
345,P0346,PrimeLine Writing 01,Office Supplies,Writing,PrimeLine,0.0,0

In [82]:
products_clean.loc[
    products_clean["Product_ID"] == "P0346",
    ["Unit_Cost", "Unit_Price"]
] = [300, 500]

In [83]:
products_clean[products_clean["Product_ID"] == "P0346"]

,Product_ID,Product_Name,Category,Subcategory,Brand,Unit_Cost,Unit_Price
345,P0346,PrimeLine Writing 01,Office Supplies,Writing,PrimeLine,300.0,500

In [84]:
print("customers_clean:", customers_clean.columns.tolist())

customers_clean: ['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Customer_Segment', 'City', 'State', 'Region', 'Signup_Date']

In [85]:
print("customers_clean:", customers_clean.columns.tolist())
print("products_clean:", products_clean.columns.tolist())
print("sellers_clean:", sellers_clean.columns.tolist())
print("orders_clean:", orders_clean.columns.tolist())
print("order_items_clean:", order_items_clean.columns.tolist())

customers_clean: ['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Customer_Segment', 'City', 'State', 'Region', 'Signup_Date']
products_clean: ['Product_ID', 'Product_Name', 'Category', 'Subcategory', 'Brand', 'Unit_Cost', 'Unit_Price']
sellers_clean: ['Seller_ID', 'Seller_Name', 'Seller_Type', 'Seller_Region']
orders_clean: ['Order_ID', 'Order_Date', 'Customer_ID', 'Seller_ID', 'Order_Status', 'Payment_Method', 'Shipping_Mode']
order_items_clean: ['Order_ID', 'Product_ID', 'Seller_ID', 'Quantity', 'Discount', 'Sales', 'Cost', 'Profit', 'Order_Status']

In [86]:
p0346_mask = order_items_clean["Product_ID"]=="P0346"

order_items_clean.loc[p0346_mask, "Sales"]=(
    500
    * order_items_clean.loc[p0346_mask, "Quantity"]
    * (1-order_items_clean.loc[p0346_mask, "Discount"])
)

order_items_clean.loc[p0346_mask, "Cost"]=(
    300
    * order_items_clean.loc[p0346_mask, "Quantity"]
)

order_items_clean.loc[p0346_mask, "Profit"]=(
    order_items_clean.loc[p0346_mask, "Sales"]
    - order_items_clean.loc[p0346_mask, "Cost"]
)

In [87]:
order_items_clean[order_items_clean["Product_ID"]=="P0346"].head()

,Order_ID,Product_ID,Seller_ID,Quantity,Discount,Sales,Cost,Profit,Order_Status
890,O0000415,P0346,S0063,1,0.08,460.0,300.0,160.0,Completed
1181,O0000547,P0346,S0027,2,0.00,1000.0,600.0,400.0,Completed
1362,O0000627,P0346,S0085,2,0.05,950.0,600.0,350.0,Completed
1501,O0000696,P0346,S0096,2,0.15,850.0,600.0,250.0,Completed
1857,O0000857,P0346,S0074,4,0.25,1500.0,1200.0,300.0,Completed

In [91]:
order_items_clean[
    order_items_clean["Product_ID"]=="P0346"][["Quantity", "Discount", "Sales", "Cost", "Profit"]].describe()

         Quantity    Discount        Sales         Cost      Profit
count  246.000000  246.000000   246.000000   246.000000  246.000000
mean     2.455285    0.105650  1101.341463   736.585366  364.756098
std      1.093596    0.075751   506.893731   328.078709  196.266014
min      1.000000    0.000000   375.000000   300.000000   75.000000
25%      1.250000    0.030000   562.500000   375.000000  185.000000
50%      2.000000    0.100000  1000.000000   600.000000  320.000000
75%      3.000000    0.150000  1500.000000   900.000000  555.000000
max      4.000000    0.250000  2000.000000  1200.000000  800.000000

In [93]:
products_clean[products_clean["Unit_Price"]==0]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Subcategory, Brand, Unit_Cost, Unit_Price]
Index: []

In [94]:
products_clean[products_clean["Unit_Cost"]==0]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Subcategory, Brand, Unit_Cost, Unit_Price]
Index: []

In [95]:
order_items_clean[order_items_clean["Sales"]==0]

Empty DataFrame
Columns: [Order_ID, Product_ID, Seller_ID, Quantity, Discount, Sales, Cost, Profit, Order_Status]
Index: []

In [96]:
print(customers_clean["Signup_Date"].dtype)

str

In [98]:
print(orders_clean["Order_Date"].dtype)

str

In [99]:
customers_clean["Signup_Date"]=pd.to_datetime(customers_clean["Signup_Date"])

In [100]:
print(customers_clean["Signup_Date"].dtype)

datetime64[us]

In [101]:
orders_clean["Order_Date"]=pd.to_datetime(orders_clean["Order_Date"])

In [102]:
print(orders_clean["Order_Date"].dtype)

datetime64[us]

In [103]:
print(customers_clean["Signup_Date"].isnull().sum())
print(orders_clean["Order_Date"].isnull().sum())

0
0

In [104]:
orders_clean["Customer_ID"].isin(customers_clean["Customer_ID"]).value_counts()

Customer_ID
True    50000
Name: count, dtype: int64

In [105]:
orders_clean["Seller_ID"].isin(
    sellers_clean["Seller_ID"]
).value_counts()

Seller_ID
True    50000
Name: count, dtype: int64

In [107]:
order_items_clean["Order_ID"].isin(
    orders_clean["Order_ID"]
).value_counts()

Order_ID
True    105953
Name: count, dtype: int64

In [108]:
order_items_clean["Product_ID"].isin(
    products_clean["Product_ID"]
).value_counts()

Product_ID
True    105953
Name: count, dtype: int64

In [109]:
order_items_clean["Seller_ID"].isin(
    sellers_clean["Seller_ID"]
).value_counts()

Seller_ID
True    105953
Name: count, dtype: int64

In [110]:
customers_clean["Customer_ID"].nunique()

2000

In [111]:
len(customers_clean)

2000

In [112]:
print("Products:", products_clean["Product_ID"].nunique(), len(products_clean))
print("Sellers:", sellers_clean["Seller_ID"].nunique(), len(sellers_clean))
print("Orders:", orders_clean["Order_ID"].nunique(), len(orders_clean))

Products: 420 420
Sellers: 100 100
Orders: 50000 50000

In [113]:
order_items_clean.duplicated(subset=["Order_ID", "Product_ID"]).sum()

np.int64(0)

In [115]:
total_sales = order_items_clean["Sales"].sum()
print("Total Sales:", total_sales)

total_cost = order_items_clean["Cost"].sum()
print("Total cost:", total_cost)

total_profit = order_items_clean["Profit"].sum()
print("Total Profit:", total_profit)

Total Sales: 2107565604.0
Total cost: 1472412030.85
Total Profit: 635153573.15

In [116]:
profit_margin = (total_profit/total_sales)*100
print("Profit Margin:", profit_margin)

Profit Margin: 30.136835216162506

In [117]:
total_orders = orders_clean["Order_ID"].nunique()
print("Total orders:", total_orders)

Total orders: 50000

In [118]:
total_customers = customers_clean["Customer_ID"].nunique()
print("Total customers:", total_customers)

Total customers: 2000

In [119]:
avg_order_per_customer = (total_orders/total_customers)
print("average order per customer:", avg_order_per_customer)

average order per customer: 25.0

In [121]:
category_analysis = order_items_clean.merge(products_clean[["Product_ID", "Category"]], on = "Product_ID", how="left")

In [122]:
category_analysis.shape

(105953, 10)

In [123]:
category_analysis["Category"].isnull().sum()

np.int64(0)

In [125]:
category_summary = category_analysis.groupby("Category").agg(
                                             total_sales = ("Sales","sum"),
                                             total_cost = ("Cost","sum"),
                                             total_profit = ("Profit", "sum"),
                                             total_quantity = ("Quantity", "sum")
                                             ).reset_index()

In [126]:
category_summary

,Category,total_sales,total_cost,total_profit,total_quantity
0,Beauty & Personal Care,6.638252e+07,4.677470e+07,1.960781e+07,37919
1,Books,3.044337e+07,2.154134e+07,8.902038e+06,37540
2,Electronics,1.013188e+09,7.029123e+08,3.102759e+08,38225
3,Fashion,1.309160e+08,9.294767e+07,3.796829e+07,38169
4,Home & Kitchen,3.228456e+08,2.311535e+08,9.169219e+07,37262
5,Office Supplies,2.834373e+08,1.989330e+08,8.450431e+07,37697
6,Sports & Fitness,2.603527e+08,1.781496e+08,8.220308e+07,37901

In [131]:
category_summary["Profit_margin"]=(category_summary["total_profit"]/category_summary["total_sales"])*100

In [132]:
category_summary.sort_values("Profit_margin", ascending=False)

,Category,total_sales,total_cost,total_profit,total_quantity,Profit_margin
6,Sports & Fitness,2.603527e+08,1.781496e+08,8.220308e+07,37901,31.573742
2,Electronics,1.013188e+09,7.029123e+08,3.102759e+08,38225,30.623715
5,Office Supplies,2.834373e+08,1.989330e+08,8.450431e+07,37697,29.814111
0,Beauty & Personal Care,6.638252e+07,4.677470e+07,1.960781e+07,37919,29.537613
1,Books,3.044337e+07,2.154134e+07,8.902038e+06,37540,29.241298
3,Fashion,1.309160e+08,9.294767e+07,3.796829e+07,38169,29.002034
4,Home & Kitchen,3.228456e+08,2.311535e+08,9.169219e+07,37262,28.401248

In [133]:
category_summary.sort_values("total_sales", ascending=False)[["Category", "total_sales", "total_profit", "Profit_margin"]]

                 Category   total_sales  total_profit  Profit_margin
2             Electronics  1.013188e+09  3.102759e+08      30.623715
4          Home & Kitchen  3.228456e+08  9.169219e+07      28.401248
5         Office Supplies  2.834373e+08  8.450431e+07      29.814111
6        Sports & Fitness  2.603527e+08  8.220308e+07      31.573742
3                 Fashion  1.309160e+08  3.796829e+07      29.002034
0  Beauty & Personal Care  6.638252e+07  1.960781e+07      29.537613
1                   Books  3.044337e+07  8.902038e+06      29.241298

In [134]:
subcategory_analysis = order_items_clean.merge(
    products_clean[["Product_ID", "Category", "Subcategory"]],
    on="Product_ID",
    how="left"
)

In [135]:
subcategory_analysis.shape

(105953, 11)

In [137]:
subcategory_analysis["Category"].isnull().sum()

np.int64(0)

In [139]:
subcategory_analysis["Subcategory"].isnull().sum()

np.int64(0)

In [140]:
subcategory_summary = subcategory_analysis.groupby(
    ["Category", "Subcategory"]
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [141]:
subcategory_summary

,Category,Subcategory,Total_Sales,Total_Cost,Total_Profit,Total_Quantity
0,Beauty & Personal Care,Haircare,15297198.0,1.051985e+07,4.777347e+06,9778
1,Beauty & Personal Care,Makeup,16981772.0,1.235887e+07,4.622900e+06,9216
2,Beauty & Personal Care,Personal Care,12129193.0,8.584512e+06,3.544681e+06,9183
3,Beauty & Personal Care,Skincare,21974352.0,1.531147e+07,6.662883e+06,9742
4,Books,Academic,11374688.0,8.070827e+06,3.303861e+06,9466
5,Books,Children,3946754.0,2.664685e+06,1.282069e+06,9362
6,Books,Fiction,5693929.0,3.944767e+06,1.749162e+06,9301
7,Books,Non-Fiction,9428003.0,6.861057e+06,2.566946e+06,9411
8,Electronics,Accessories,25984240.0,1.789793e+07,8.086309e+06,9342
9,Electronics,Audio,103516928.0,7.211341e+07,3.140351e+07,9728
10,Electronics,Laptops,523008552.0,3.697167e+08,1.532918e+08,9642
11,Electronics,Smartphones,360678441.0,2.431842e+08,1.174942e+08,9513
12,Fashion,Accessories,30483726.0,2.147465e+07,9.009079e+06,9563
13,Fashion,Footwear,41790948.0,3.051274e+07,1.127821e+07,9476
14,Fashion,Men,27137011.0,1.942435e+07,7.712664e+06,9855
15,Fashion,Women,31504274.0,2.153593e+07,9.968343e+06,9275
16,Home & Kitchen,Furniture,159708427.0,1.151216e+08,4.458678e+07,9311
17,Home & Kitchen,Home Decor,47513308.0,3.312051e+07,1.439279e+07,9762
18,Home & Kitchen,Kitchen Appliances,81030083.0,5.895012e+07,2.207996e+07,9146
19,Home & Kitchen,Storage,34593827.0,2.396117e+07,1.063266e+07,9043
20,Office Supplies,Office Furniture,107303246.0,7.471475e+07,3.258849e+07,9463
21,Office Supplies,Printers,165311786.0,1.163692e+08,4.894263e+07,9347
22,Office Supplies,Stationery,6630403.0,4.915512e+06,1.714891e+06,9552
23,Office Supplies,Writing,4191854.0,2.933564e+06,1.258290e+06,9335
24,Sports & Fitness,Accessories,26308111.0,1.754833e+07,8.759782e+06,9458
25,Sports & Fitness,Fitness Equipment,146118765.0,1.027817e+08,4.333710e+07,9570
26,Sports & Fitness,Outdoor,59914127.0,3.888032e+07,2.103381e+07,9589
27,Sports & Fitness,Sportswear,28011658.0,1.893927e+07,9.072385e+06,9284

In [142]:
subcategory_summary["Profit_Margin"] = (
    subcategory_summary["Total_Profit"]
    / subcategory_summary["Total_Sales"]
) * 100

In [143]:
subcategory_summary.sort_values(
    "Profit_Margin",
    ascending=False
)

,Category,Subcategory,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Profit_Margin
26,Sports & Fitness,Outdoor,59914127.0,3.888032e+07,2.103381e+07,9589,35.106591
24,Sports & Fitness,Accessories,26308111.0,1.754833e+07,8.759782e+06,9458,33.296886
11,Electronics,Smartphones,360678441.0,2.431842e+08,1.174942e+08,9513,32.575894
5,Books,Children,3946754.0,2.664685e+06,1.282069e+06,9362,32.484129
27,Sports & Fitness,Sportswear,28011658.0,1.893927e+07,9.072385e+06,9284,32.387890
15,Fashion,Women,31504274.0,2.153593e+07,9.968343e+06,9275,31.641239
0,Beauty & Personal Care,Haircare,15297198.0,1.051985e+07,4.777347e+06,9778,31.230209
8,Electronics,Accessories,25984240.0,1.789793e+07,8.086309e+06,9342,31.120053
19,Home & Kitchen,Storage,34593827.0,2.396117e+07,1.063266e+07,9043,30.735707
6,Books,Fiction,5693929.0,3.944767e+06,1.749162e+06,9301,30.719779
20,Office Supplies,Office Furniture,107303246.0,7.471475e+07,3.258849e+07,9463,30.370463
9,Electronics,Audio,103516928.0,7.211341e+07,3.140351e+07,9728,30.336597
3,Beauty & Personal Care,Skincare,21974352.0,1.531147e+07,6.662883e+06,9742,30.321179
17,Home & Kitchen,Home Decor,47513308.0,3.312051e+07,1.439279e+07,9762,30.292132
23,Office Supplies,Writing,4191854.0,2.933564e+06,1.258290e+06,9335,30.017496
25,Sports & Fitness,Fitness Equipment,146118765.0,1.027817e+08,4.333710e+07,9570,29.658821
21,Office Supplies,Printers,165311786.0,1.163692e+08,4.894263e+07,9347,29.606258
12,Fashion,Accessories,30483726.0,2.147465e+07,9.009079e+06,9563,29.553731
10,Electronics,Laptops,523008552.0,3.697167e+08,1.532918e+08,9642,29.309618
2,Beauty & Personal Care,Personal Care,12129193.0,8.584512e+06,3.544681e+06,9183,29.224378
4,Books,Academic,11374688.0,8.070827e+06,3.303861e+06,9466,29.045724
14,Fashion,Men,27137011.0,1.942435e+07,7.712664e+06,9855,28.421200
16,Home & Kitchen,Furniture,159708427.0,1.151216e+08,4.458678e+07,9311,27.917611
18,Home & Kitchen,Kitchen Appliances,81030083.0,5.895012e+07,2.207996e+07,9146,27.249092
7,Books,Non-Fiction,9428003.0,6.861057e+06,2.566946e+06,9411,27.226829
1,Beauty & Personal Care,Makeup,16981772.0,1.235887e+07,4.622900e+06,9216,27.222717
13,Fashion,Footwear,41790948.0,3.051274e+07,1.127821e+07,9476,26.987198
22,Office Supplies,Stationery,6630403.0,4.915512e+06,1.714891e+06,9552,25.864054

In [144]:
product_analysis = order_items_clean.merge(
    products_clean[["Product_ID", "Product_Name", "Category", "Subcategory", "Brand"]],
    on="Product_ID",
    how="left"
)

In [145]:
product_analysis.shape

(105953, 13)

In [146]:
product_analysis["Product_Name"].isnull().sum()

np.int64(0)

In [147]:
product_summary = product_analysis.groupby(
    ["Product_ID", "Product_Name", "Category", "Subcategory", "Brand"]
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [148]:
top_products_sales = product_summary.sort_values(
    "Total_Sales",
    ascending=False
)

In [149]:
top_products_sales.head(10)

,Product_ID,Product_Name,Category,Subcategory,Brand,Total_Sales,Total_Cost,Total_Profit,Total_Quantity
8,P0009,Everday Laptops 09,Electronics,Laptops,Everday,54272426.0,40472544.00,13799882.00,687
6,P0007,Vista Laptops 07,Electronics,Laptops,Vista,46336444.0,25697346.00,20639098.00,600
13,P0014,Aero Laptops 14,Electronics,Laptops,Aero,44597389.0,38787834.00,5809555.00,600
12,P0013,HomeCraft Laptops 13,Electronics,Laptops,HomeCraft,41610158.0,22812343.43,18797814.57,683
7,P0008,CorePlus Laptops 08,Electronics,Laptops,CorePlus,40649445.0,29215464.32,11433980.68,584
27,P0028,CorePlus Smartphones 13,Electronics,Smartphones,CorePlus,37761306.0,29507446.08,8253859.92,672
20,P0021,NovaTech Smartphones 06,Electronics,Smartphones,NovaTech,37336782.0,25502043.75,11834738.25,625
17,P0018,CorePlus Smartphones 03,Electronics,Smartphones,CorePlus,36131758.0,26878066.80,9253691.20,690
15,P0016,PrimeLine Smartphones 01,Electronics,Smartphones,PrimeLine,35158410.0,19046605.72,16111804.28,628
1,P0002,UrbanEdge Laptops 02,Electronics,Laptops,UrbanEdge,34640694.0,18914650.72,15726043.28,674

In [150]:
top_products_profit = product_summary.sort_values(
    "Total_Profit",
    ascending=False
)

In [151]:
top_products_profit.head(10)

,Product_ID,Product_Name,Category,Subcategory,Brand,Total_Sales,Total_Cost,Total_Profit,Total_Quantity
6,P0007,Vista Laptops 07,Electronics,Laptops,Vista,46336444.0,25697346.00,20639098.00,600
12,P0013,HomeCraft Laptops 13,Electronics,Laptops,HomeCraft,41610158.0,22812343.43,18797814.57,683
15,P0016,PrimeLine Smartphones 01,Electronics,Smartphones,PrimeLine,35158410.0,19046605.72,16111804.28,628
1,P0002,UrbanEdge Laptops 02,Electronics,Laptops,UrbanEdge,34640694.0,18914650.72,15726043.28,674
8,P0009,Everday Laptops 09,Electronics,Laptops,Everday,54272426.0,40472544.00,13799882.00,687
10,P0011,NovaTech Laptops 11,Electronics,Laptops,NovaTech,33164172.0,20824404.75,12339767.25,675
25,P0026,PrimeLine Smartphones 11,Electronics,Smartphones,PrimeLine,27938984.0,15602571.44,12336412.56,629
20,P0021,NovaTech Smartphones 06,Electronics,Smartphones,NovaTech,37336782.0,25502043.75,11834738.25,625
7,P0008,CorePlus Laptops 08,Electronics,Laptops,CorePlus,40649445.0,29215464.32,11433980.68,584
16,P0017,Vista Smartphones 02,Electronics,Smartphones,Vista,31267925.0,20682560.01,10585364.99,581

In [152]:
product_summary["Profit_Margin"] = (
    product_summary["Total_Profit"]
    / product_summary["Total_Sales"]
) * 100

top_margin_products = product_summary.sort_values(
    "Profit_Margin",
    ascending=False
)

top_margin_products.head(10)

,Product_ID,Product_Name,Category,Subcategory,Brand,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Profit_Margin
15,P0016,PrimeLine Smartphones 01,Electronics,Smartphones,PrimeLine,35158410.0,19046605.72,16111804.28,628,45.826317
183,P0184,Aero Skincare 04,Beauty & Personal Care,Skincare,Aero,1716561.0,931161.77,785399.23,583,45.754228
239,P0240,BrightLife Makeup 15,Beauty & Personal Care,Makeup,BrightLife,1430892.0,777091.26,653800.74,589,45.691830
69,P0070,BrightLife Kitchen Appliances 10,Home & Kitchen,Kitchen Appliances,BrightLife,3372600.0,1832664.68,1539935.32,668,45.660183
77,P0078,CorePlus Furniture 03,Home & Kitchen,Furniture,CorePlus,14086800.0,7676981.25,6409818.75,625,45.502305
1,P0002,UrbanEdge Laptops 02,Electronics,Laptops,UrbanEdge,34640694.0,18914650.72,15726043.28,674,45.397599
366,P0367,Vista Fitness Equipment 07,Sports & Fitness,Fitness Equipment,Vista,15246960.0,8351915.88,6895044.12,627,45.222419
12,P0013,HomeCraft Laptops 13,Electronics,Laptops,HomeCraft,41610158.0,22812343.43,18797814.57,683,45.176023
197,P0198,CorePlus Haircare 03,Beauty & Personal Care,Haircare,CorePlus,1315138.0,721034.82,594103.18,669,45.174208
297,P0298,CorePlus Children 13,Books,Children,CorePlus,351694.0,192917.58,158776.42,563,45.146184

In [153]:
customer_analysis = order_items_clean.merge(
    orders_clean[["Order_ID", "Customer_ID", "Order_Date"]],
    on="Order_ID",
    how="left"
)

customer_analysis.shape

(105953, 11)

In [154]:
customer_analysis["Customer_ID"].isnull().sum()

np.int64(0)

In [155]:
customer_summary = customer_analysis.groupby("Customer_ID").agg(
    Total_Orders=("Order_ID", "nunique"),
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [156]:
customer_summary.shape

(2000, 5)

In [158]:
top_customers_sales = customer_summary.sort_values(
    "Total_Sales",
    ascending=False
)

top_customers_sales.head(10)

     Customer_ID  Total_Orders  Total_Sales  Total_Profit  Total_Quantity
1562      C01563            30    2436182.0     786725.66             206
1214      C01215            34    2218266.0     657229.97             179
397       C00398            27    2183761.0     687831.12             147
1255      C01256            31    2182545.0     614892.06             187
1677      C01678            37    2176229.0     505761.90             210
478       C00479            30    2171074.0     680767.34             186
1444      C01445            27    2165343.0     686781.47             146
1879      C01880            23    2145118.0     598369.82             142
1394      C01395            26    2131464.0     651783.94             188
733       C00734            29    2112479.0     517247.02             184

In [159]:
top_customers_profit = customer_summary.sort_values(
    "Total_Profit",
    ascending=False
)

top_customers_profit.head(10)

     Customer_ID  Total_Orders  Total_Sales  Total_Profit  Total_Quantity
1562      C01563            30    2436182.0     786725.66             206
172       C00173            27    2059416.0     752843.25             152
117       C00118            28    1954560.0     732428.35             173
613       C00614            35    2061446.0     714146.98             208
889       C00890            22    2095110.0     706855.72             144
1611      C01612            27    2089560.0     704441.41             145
1855      C01856            29    1913522.0     691487.60             142
397       C00398            27    2183761.0     687831.12             147
1444      C01445            27    2165343.0     686781.47             146
1323      C01324            27    2037419.0     680771.82             150

In [160]:
customer_summary["Average_Order_Value"] = (customer_summary["Total_Sales"]/customer_summary["Total_Orders"])

In [162]:
top_customers_aov = customer_summary.sort_values("Average_Order_Value",ascending=False)

In [163]:
top_customers_aov.head(10)

,Customer_ID,Total_Orders,Total_Sales,Total_Profit,Total_Quantity,Average_Order_Value
889,C00890,22,2095110.0,706855.72,144,95232.272727
1879,C01880,23,2145118.0,598369.82,142,93266.000000
332,C00333,19,1626492.0,515597.43,111,85604.842105
1260,C01261,19,1602420.0,510597.55,122,84337.894737
1394,C01395,26,2131464.0,651783.94,188,81979.384615
1562,C01563,30,2436182.0,786725.66,206,81206.066667
1622,C01623,22,1783182.0,598462.99,111,81053.727273
397,C00398,27,2183761.0,687831.12,147,80880.037037
1444,C01445,27,2165343.0,686781.47,146,80197.888889
773,C00774,19,1517289.0,490919.87,145,79857.315789

In [164]:
customer_summary["Profit_Margin"] = (
    customer_summary["Total_Profit"]
    / customer_summary["Total_Sales"]
) * 100

In [165]:
top_customers_margin = customer_summary.sort_values(
    "Profit_Margin",
    ascending=False
)

In [166]:
top_customers_margin.head(10)

,Customer_ID,Total_Orders,Total_Sales,Total_Profit,Total_Quantity,Average_Order_Value,Profit_Margin
1079,C01080,16,861973.0,361550.02,79,53873.312500,41.944472
789,C00790,20,1018095.0,416260.50,101,50904.750000,40.886214
1823,C01824,23,1155517.0,466848.48,145,50239.869565,40.401697
529,C00530,19,783513.0,315282.98,91,41237.526316,40.239662
770,C00771,25,1454744.0,578119.93,140,58189.760000,39.740321
627,C00628,17,603051.0,237409.74,85,35473.588235,39.368103
444,C00445,19,1168539.0,457369.53,111,61502.052632,39.140288
1462,C01463,27,1556464.0,608990.80,130,57646.814815,39.126559
1230,C01231,22,645725.0,252045.97,116,29351.136364,39.033020
1123,C01124,23,935322.0,363746.54,128,40666.173913,38.889980

In [167]:
order_status_summary = orders_clean["Order_Status"].value_counts()

In [168]:
order_status_summary

Order_Status
Completed    42954
Cancelled     2512
Returned      2487
Pending       2047
Name: count, dtype: int64

In [169]:
order_status_percentage = (
    orders_clean["Order_Status"]
    .value_counts(normalize=True)
    * 100
)

In [170]:
order_status_percentage

Order_Status
Completed    85.908
Cancelled     5.024
Returned      4.974
Pending       4.094
Name: proportion, dtype: float64

In [171]:
cancellation_rate = (
    (orders_clean["Order_Status"] == "Cancelled").sum()
    / len(orders_clean)
) * 100

In [172]:
return_rate = (
    (orders_clean["Order_Status"] == "Returned").sum()
    / len(orders_clean)
) * 100

In [173]:
print(f"Cancellation Rate: {cancellation_rate:.2f}%")
print(f"Return Rate: {return_rate:.2f}%")

Cancellation Rate: 5.02%
Return Rate: 4.97%

In [174]:
orders_clean["Payment_Method"].value_counts()

Payment_Method
Wallet         8542
Credit Card    8416
Debit Card     8363
UPI            8261
Net Banking    8259
COD            8159
Name: count, dtype: int64

In [175]:
orders_clean["Payment_Method"].value_counts(normalize=True) * 100

Payment_Method
Wallet         17.084
Credit Card    16.832
Debit Card     16.726
UPI            16.522
Net Banking    16.518
COD            16.318
Name: proportion, dtype: float64

In [177]:
payment_status = pd.crosstab(
    orders_clean["Payment_Method"],
    orders_clean["Order_Status"]
)

payment_status

Order_Status    Cancelled  Completed  Pending  Returned
Payment_Method
COD                   404       7068      303       384
Credit Card           440       7245      312       419
Debit Card            429       7181      349       404
Net Banking           395       7056      374       434
UPI                   424       7074      355       408
Wallet                420       7330      354       438

In [178]:
payment_status_pct = pd.crosstab(
    orders_clean["Payment_Method"],
    orders_clean["Order_Status"],
    normalize="index"
) * 100

In [179]:
payment_status_pct.round(2)

Order_Status    Cancelled  Completed  Pending  Returned
Payment_Method
COD                  4.95      86.63     3.71      4.71
Credit Card          5.23      86.09     3.71      4.98
Debit Card           5.13      85.87     4.17      4.83
Net Banking          4.78      85.43     4.53      5.25
UPI                  5.13      85.63     4.30      4.94
Wallet               4.92      85.81     4.14      5.13

In [180]:
orders_clean["Shipping_Mode"].value_counts()

Shipping_Mode
Same Day    16830
Standard    16595
Express     16575
Name: count, dtype: int64

In [181]:
orders_clean["Shipping_Mode"].value_counts(normalize=True) * 100

Shipping_Mode
Same Day    33.66
Standard    33.19
Express     33.15
Name: proportion, dtype: float64

In [182]:
shipping_status = pd.crosstab(
    orders_clean["Shipping_Mode"],
    orders_clean["Order_Status"]
)

shipping_status

Order_Status   Cancelled  Completed  Pending  Returned
Shipping_Mode
Express              874      14222      669       810
Same Day             799      14492      698       841
Standard             839      14240      680       836

In [183]:
shipping_status_pct = pd.crosstab(
    orders_clean["Shipping_Mode"],
    orders_clean["Order_Status"],
    normalize="index"
) * 100

In [184]:
shipping_status_pct.round(2)

Order_Status   Cancelled  Completed  Pending  Returned
Shipping_Mode
Express             5.27      85.80     4.04      4.89
Same Day            4.75      86.11     4.15      5.00
Standard            5.06      85.81     4.10      5.04

In [187]:
%whos

Variable                  Type         Data/Info
------------------------------------------------
avg_order_per_customer    float        25.0
cancellation_rate         float64      5.024
category_analysis         DataFrame    Shape: (105953, 10)
category_summary          DataFrame    Shape: (7, 6)
customer_analysis         DataFrame    Shape: (105953, 11)
customer_summary          DataFrame    Shape: (2000, 7)
customers                 DataFrame    Shape: (2000, 9)
customers_clean           DataFrame    Shape: (2000, 9)
np                        module       <module 'numpy' from '/Li<...>kages/numpy/__init__.py'>
order_items               DataFrame    Shape: (105953, 9)
order_items_clean         DataFrame    Shape: (105953, 9)
order_status_percentage   Series       Shape: (4,)
order_status_summary      Series       Shape: (4,)
orders                    DataFrame    Shape: (50000, 7)
orders_clean              DataFrame    Shape: (50000, 7)
p0346_mask                Series       Shape: (105953,)
payment_status            DataFrame    Shape: (6, 4)
payment_status_pct        DataFrame    Shape: (6, 4)
pd                        module       <module 'pandas' from '/L<...>ages/pandas/__init__.py'>
product_analysis          DataFrame    Shape: (105953, 13)
product_summary           DataFrame    Shape: (420, 10)
products                  DataFrame    Shape: (420, 7)
products_clean            DataFrame    Shape: (420, 7)
profit_margin             float64      30.136835216162506
return_rate               float64      4.974
sellers                   DataFrame    Shape: (100, 4)
sellers_clean             DataFrame    Shape: (100, 4)
shipping_status           DataFrame    Shape: (3, 4)
shipping_status_pct       DataFrame    Shape: (3, 4)
subcategory_analysis      DataFrame    Shape: (105953, 11)
subcategory_summary       DataFrame    Shape: (28, 7)
top_customers_aov         DataFrame    Shape: (2000, 6)
top_customers_margin      DataFrame    Shape: (2000, 7)
top_customers_profit      DataFrame    Shape: (2000, 5)
top_customers_sales       DataFrame    Shape: (2000, 5)
top_margin_products       DataFrame    Shape: (420, 10)
top_products_profit       DataFrame    Shape: (420, 9)
top_products_sales        DataFrame    Shape: (420, 9)
total_cost                float64      1472412030.85
total_customers           int          2000
total_orders              int          50000
total_profit              float64      635153573.15
total_sales               float64      2107565604.0

In [188]:
product_analysis.columns

Index(['Order_ID', 'Product_ID', 'Seller_ID', 'Quantity', 'Discount', 'Sales',
       'Cost', 'Profit', 'Order_Status', 'Product_Name', 'Category',
       'Subcategory', 'Brand'],
      dtype='str')

In [189]:
seller_summary = product_analysis.groupby("Seller_ID").agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [190]:
top_sellers_sales = seller_summary.sort_values(
    "Total_Sales",
    ascending=False
)

In [191]:
top_sellers_sales.head(10)

   Seller_ID  Total_Sales   Total_Cost  Total_Profit  Total_Quantity
47     S0048   24173081.0  17005850.54    7167230.46            2960
56     S0057   23919107.0  16542891.49    7376215.51            2934
35     S0036   23718035.0  16879012.18    6839022.82            2811
53     S0054   23551003.0  16709228.33    6841774.67            2859
98     S0099   23441296.0  16437413.52    7003882.48            2826
49     S0050   23400216.0  16558420.59    6841795.41            2810
82     S0083   23382847.0  16283753.36    7099093.64            2787
45     S0046   23299104.0  16111130.57    7187973.43            2910
96     S0097   23290057.0  16120316.75    7169740.25            2619
15     S0016   23176626.0  16123390.19    7053235.81            2853

In [192]:
top_sellers_profit = seller_summary.sort_values(
    "Total_Profit",
    ascending=False
)

In [193]:
top_sellers_profit.head(10)

   Seller_ID  Total_Sales   Total_Cost  Total_Profit  Total_Quantity
56     S0057   23919107.0  16542891.49    7376215.51            2934
45     S0046   23299104.0  16111130.57    7187973.43            2910
22     S0023   22302308.0  15119807.61    7182500.39            2889
96     S0097   23290057.0  16120316.75    7169740.25            2619
47     S0048   24173081.0  17005850.54    7167230.46            2960
82     S0083   23382847.0  16283753.36    7099093.64            2787
15     S0016   23176626.0  16123390.19    7053235.81            2853
98     S0099   23441296.0  16437413.52    7003882.48            2826
85     S0086   23126656.0  16185272.90    6941383.10            2797
89     S0090   22103340.0  15193483.00    6909857.00            2775

In [194]:
seller_summary["Profit_Margin"] = (
    seller_summary["Total_Profit"]
    / seller_summary["Total_Sales"]
) * 100

In [195]:
top_sellers_margin = seller_summary.sort_values(
    "Profit_Margin",
    ascending=False
)

In [196]:
top_sellers_margin.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Profit_Margin
61,S0062,20452985.0,13784234.35,6668750.65,2618,32.605268
22,S0023,22302308.0,15119807.61,7182500.39,2889,32.205189
86,S0087,20517989.0,14019327.18,6498661.82,2590,31.672996
25,S0026,19462985.0,13349353.63,6113631.37,2649,31.411581
18,S0019,21502171.0,14759086.04,6743084.96,2603,31.360019
52,S0053,21576025.0,14821518.84,6754506.16,2406,31.305610
89,S0090,22103340.0,15193483.00,6909857.00,2775,31.261597
27,S0028,22002077.0,15125363.64,6876713.36,2687,31.254837
7,S0008,19842819.0,13666953.06,6175865.94,2561,31.123934
36,S0037,21389914.0,14741335.88,6648578.12,2540,31.082772

In [197]:
seller_orders = product_analysis.groupby("Seller_ID")["Order_ID"].nunique().reset_index(
    name="Total_Orders"
)

In [198]:
seller_orders = seller_orders.sort_values(
    "Total_Orders",
    ascending=False
)

In [199]:
seller_orders.head(10)

   Seller_ID  Total_Orders
47     S0048           553
63     S0064           550
41     S0042           550
9      S0010           543
53     S0054           540
98     S0099           539
45     S0046           536
56     S0057           535
35     S0036           534
1      S0002           534

In [1]:
seller_performance = seller_summary.merge(
    seller_orders,
    on="Seller_ID"
)

NameError: name 'seller_summary' is not defined

In [2]:
%whos

Interactive namespace is empty.

In [3]:
import os

os.listdir()

['customers.csv',
 'products.csv',
 'orders.csv',
 'Untitled.ipynb',
 'sellers.csv',
 '.ipynb_checkpoints',
 'order_items.csv']

In [4]:
import pandas as pd
import numpy as np

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
sellers = pd.read_csv("sellers.csv")
order_items = pd.read_csv("order_items.csv")

In [5]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Sellers:", sellers.shape)
print("Order Items:", order_items.shape)

Customers: (2000, 9)
Products: (420, 7)
Orders: (50000, 7)
Sellers: (100, 4)
Order Items: (105953, 9)

In [6]:
print("Customers:")
print(customers.info())

print("\nProducts:")
print(products.info())

print("\nOrders:")
print(orders.info())

print("\nSellers:")
print(sellers.info())

print("\nOrder Items:")
print(order_items.info())

Customers:
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       2000 non-null   str
 1   Customer_Name     2000 non-null   str
 2   Gender            2000 non-null   str
 3   Age               2000 non-null   int64
 4   Customer_Segment  2000 non-null   str
 5   City              2000 non-null   str
 6   State             2000 non-null   str
 7   Region            2000 non-null   str
 8   Signup_Date       2000 non-null   str
dtypes: int64(1), str(8)
memory usage: 140.8 KB
None

Products:
<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    420 non-null    str
 1   Product_Name  420 non-null    str
 2   Category      420 non-null    str
 3   Subcategory   420 non-null    str
 4   Brand         420 non-null    str
 5   Unit_Cost     420 non-null    float64
 6   Unit_Price    420 non-null    int64
dtypes: float64(1), int64(1), str(5)
memory usage: 23.1 KB
None

Orders:
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50000 non-null  str
 1   Order_Date      50000 non-null  str
 2   Customer_ID     50000 non-null  str
 3   Seller_ID       50000 non-null  str
 4   Order_Status    50000 non-null  str
 5   Payment_Method  50000 non-null  str
 6   Shipping_Mode   50000 non-null  str
dtypes: str(7)
memory usage: 2.7 MB
None

Sellers:
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Seller_ID      100 non-null    str
 1   Seller_Name    100 non-null    str
 2   Seller_Type    100 non-null    str
 3   Seller_Region  100 non-null    str
dtypes: str(4)
memory usage: 3.3 KB
None

Order Items:
<class 'pandas.DataFrame'>
RangeIndex: 105953 entries, 0 to 105952
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Order_ID      105953 non-null  str
 1   Product_ID    105953 non-null  str
 2   Seller_ID     105953 non-null  str
 3   Quantity      105953 non-null  int64
 4   Discount      105953 non-null  float64
 5   Sales         105953 non-null  float64
 6   Cost          105953 non-null  float64
 7   Profit        105953 non-null  float64
 8   Order_Status  105953 non-null  str
dtypes: float64(4), int64(1), str(4)
memory usage: 7.3 MB
None

In [7]:
customers_clean = customers.copy()
products_clean = products.copy()
orders_clean = orders.copy()
sellers_clean = sellers.copy()
order_items_clean = order_items.copy()

In [8]:
customers_clean["Signup_Date"] = pd.to_datetime(
    customers_clean["Signup_Date"]
)

orders_clean["Order_Date"] = pd.to_datetime(
    orders_clean["Order_Date"]
)

In [9]:
print(customers_clean.dtypes)
print(orders_clean.dtypes)

Customer_ID                    str
Customer_Name                  str
Gender                         str
Age                          int64
Customer_Segment               str
City                           str
State                          str
Region                         str
Signup_Date         datetime64[us]
dtype: object
Order_ID                     str
Order_Date        datetime64[us]
Customer_ID                  str
Seller_ID                    str
Order_Status                 str
Payment_Method               str
Shipping_Mode                str
dtype: object

In [10]:
product_analysis = order_items_clean.merge(
    products_clean[
        [
            "Product_ID",
            "Product_Name",
            "Category",
            "Subcategory",
            "Brand"
        ]
    ],
    on="Product_ID",
    how="left"
)

In [11]:
print(product_analysis.shape)
print(product_analysis.columns)

(105953, 13)
Index(['Order_ID', 'Product_ID', 'Seller_ID', 'Quantity', 'Discount', 'Sales',
       'Cost', 'Profit', 'Order_Status', 'Product_Name', 'Category',
       'Subcategory', 'Brand'],
      dtype='str')

In [12]:
product_analysis = order_items_clean.merge(
    products_clean[
        [
            "Product_ID",
            "Product_Name",
            "Category",
            "Subcategory",
            "Brand"
        ]
    ],
    on="Product_ID",
    how="left"
)

In [13]:
print(product_analysis.shape)
print(product_analysis.columns)

(105953, 13)
Index(['Order_ID', 'Product_ID', 'Seller_ID', 'Quantity', 'Discount', 'Sales',
       'Cost', 'Profit', 'Order_Status', 'Product_Name', 'Category',
       'Subcategory', 'Brand'],
      dtype='str')

In [14]:
print("Total Sales:", product_analysis["Sales"].sum())
print("Total Cost:", product_analysis["Cost"].sum())
print("Total Profit:", product_analysis["Profit"].sum())
print("Total Quantity:", product_analysis["Quantity"].sum())

Total Sales: 2107294674.0
Total Cost: 1472230830.85
Total Profit: 635063843.15
Total Quantity: 264713

In [15]:
seller_summary = product_analysis.groupby("Seller_ID").agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [16]:
seller_orders = product_analysis.groupby("Seller_ID")["Order_ID"].nunique().reset_index(
    name="Total_Orders"
)

In [17]:
seller_performance = seller_summary.merge(
    seller_orders,
    on="Seller_ID"
)

In [18]:
seller_performance["Profit_Per_Order"] = (
    seller_performance["Total_Profit"]
    / seller_performance["Total_Orders"]
)

In [19]:
top_sellers_profit_per_order = seller_performance.sort_values(
    "Profit_Per_Order",
    ascending=False
)

In [20]:
top_sellers_profit_per_order.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Total_Orders,Profit_Per_Order
96,S0097,23287352.0,16118516.75,7168835.25,2619,487,14720.400924
52,S0053,21574720.0,14820618.84,6754101.16,2406,463,14587.691490
58,S0059,21447202.0,14846355.90,6600846.10,2449,467,14134.574090
22,S0023,22302308.0,15119807.61,7182500.39,2889,515,13946.602699
16,S0017,21850127.0,15100899.66,6749227.34,2607,484,13944.684587
85,S0086,23120651.0,16181372.90,6939278.10,2797,498,13934.293373
82,S0083,23381007.0,16282553.36,7098453.64,2787,514,13810.221089
56,S0057,23917672.0,16541991.49,7375680.51,2934,535,13786.318710
84,S0085,22344108.0,15688333.96,6655774.04,2593,483,13780.070476
89,S0090,22100960.0,15191683.00,6909277.00,2775,505,13681.736634

In [21]:
seller_performance["Average_Order_Value"] = (
    seller_performance["Total_Sales"]
    / seller_performance["Total_Orders"]
)

In [22]:
top_sellers_aov = seller_performance.sort_values(
    "Average_Order_Value",
    ascending=False
)

In [23]:
top_sellers_aov.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Total_Orders,Profit_Per_Order,Average_Order_Value
96,S0097,23287352.0,16118516.75,7168835.25,2619,487,14720.400924,47817.971253
52,S0053,21574720.0,14820618.84,6754101.16,2406,463,14587.691490,46597.667387
85,S0086,23120651.0,16181372.90,6939278.10,2797,498,13934.293373,46427.010040
84,S0085,22344108.0,15688333.96,6655774.04,2593,483,13780.070476,46261.093168
58,S0059,21447202.0,14846355.90,6600846.10,2449,467,14134.574090,45925.486081
65,S0066,20488400.0,14356182.88,6132217.12,2316,450,13627.149156,45529.777778
82,S0083,23381007.0,16282553.36,7098453.64,2787,514,13810.221089,45488.340467
16,S0017,21850127.0,15100899.66,6749227.34,2607,484,13944.684587,45144.890496
49,S0050,23400216.0,16558420.59,6841795.41,2810,520,13157.298865,45000.415385
12,S0013,21538183.0,15166217.61,6371965.39,2572,479,13302.641733,44964.891441

In [24]:
seller_performance["Avg_Quantity_Per_Order"] = (
    seller_performance["Total_Quantity"]
    / seller_performance["Total_Orders"]
)

In [25]:
top_sellers_quantity_per_order = seller_performance.sort_values(
    "Avg_Quantity_Per_Order",
    ascending=False
)

In [26]:
top_sellers_quantity_per_order.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Total_Orders,Profit_Per_Order,Average_Order_Value,Avg_Quantity_Per_Order
30,S0031,22184922.0,15460217.40,6724704.60,2895,511,13159.891585,43414.720157,5.665362
85,S0086,23120651.0,16181372.90,6939278.10,2797,498,13934.293373,46427.010040,5.616466
22,S0023,22302308.0,15119807.61,7182500.39,2889,515,13946.602699,43305.452427,5.609709
28,S0029,22951901.0,16075149.67,6876751.33,2905,518,13275.581718,44308.689189,5.608108
37,S0038,21697183.0,15300589.73,6396593.27,2876,519,12324.842524,41805.747592,5.541426
1,S0002,22542991.0,15790032.73,6752958.27,2948,534,12645.989270,42215.338951,5.520599
4,S0005,21567027.0,15286286.14,6280740.86,2787,505,12437.110614,42706.984158,5.518812
91,S0092,22837221.0,16087332.00,6749889.00,2857,519,13005.566474,44002.352601,5.504817
89,S0090,22100960.0,15191683.00,6909277.00,2775,505,13681.736634,43764.277228,5.495050
56,S0057,23917672.0,16541991.49,7375680.51,2934,535,13786.318710,44705.928972,5.484112

In [27]:
seller_performance["Sales_Per_Unit"] = (
    seller_performance["Total_Sales"]
    / seller_performance["Total_Quantity"]
)

In [28]:
top_sellers_sales_per_unit = seller_performance.sort_values(
    "Sales_Per_Unit",
    ascending=False
)

In [29]:
top_sellers_sales_per_unit.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Total_Orders,Profit_Per_Order,Average_Order_Value,Avg_Quantity_Per_Order,Sales_Per_Unit
52,S0053,21574720.0,14820618.84,6754101.16,2406,463,14587.691490,46597.667387,5.196544,8967.049044
96,S0097,23287352.0,16118516.75,7168835.25,2619,487,14720.400924,47817.971253,5.377823,8891.696067
65,S0066,20488400.0,14356182.88,6132217.12,2316,450,13627.149156,45529.777778,5.146667,8846.459413
58,S0059,21447202.0,14846355.90,6600846.10,2449,467,14134.574090,45925.486081,5.244111,8757.534504
84,S0085,22344108.0,15688333.96,6655774.04,2593,483,13780.070476,46261.093168,5.368530,8617.087543
67,S0068,20955431.0,14615118.91,6340312.09,2432,475,13348.025453,44116.696842,5.120000,8616.542352
14,S0015,21618828.0,15030204.93,6588623.07,2539,495,13310.349636,43674.400000,5.129293,8514.701851
35,S0036,23714135.0,16876612.18,6837522.82,2811,534,12804.349850,44408.492509,5.264045,8436.191747
36,S0037,21385659.0,14738635.88,6647023.12,2540,494,13455.512389,43290.807692,5.141700,8419.550787
82,S0083,23381007.0,16282553.36,7098453.64,2787,514,13810.221089,45488.340467,5.422179,8389.310011

In [30]:
seller_performance["Profit_Per_Unit"] = (
    seller_performance["Total_Profit"]
    / seller_performance["Total_Quantity"]
)

In [31]:
top_sellers_profit_per_unit = seller_performance.sort_values(
    "Profit_Per_Unit",
    ascending=False
)

In [32]:
top_sellers_profit_per_unit.head(10)

,Seller_ID,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Total_Orders,Profit_Per_Order,Average_Order_Value,Avg_Quantity_Per_Order,Sales_Per_Unit,Profit_Per_Unit
52,S0053,21574720.0,14820618.84,6754101.16,2406,463,14587.691490,46597.667387,5.196544,8967.049044,2807.190840
96,S0097,23287352.0,16118516.75,7168835.25,2619,487,14720.400924,47817.971253,5.377823,8891.696067,2737.241409
58,S0059,21447202.0,14846355.90,6600846.10,2449,467,14134.574090,45925.486081,5.244111,8757.534504,2695.323030
65,S0066,20488400.0,14356182.88,6132217.12,2316,450,13627.149156,45529.777778,5.146667,8846.459413,2647.762142
36,S0037,21385659.0,14738635.88,6647023.12,2540,494,13455.512389,43290.807692,5.141700,8419.550787,2616.938236
67,S0068,20955431.0,14615118.91,6340312.09,2432,475,13348.025453,44116.696842,5.120000,8616.542352,2607.036221
14,S0015,21618828.0,15030204.93,6588623.07,2539,495,13310.349636,43674.400000,5.129293,8514.701851,2594.967731
18,S0019,21501686.0,14758786.04,6742899.96,2603,514,13118.482412,41832.073930,5.064202,8260.348060,2590.434099
16,S0017,21850127.0,15100899.66,6749227.34,2607,484,13944.684587,45144.890496,5.386364,8381.329881,2588.886590
84,S0085,22344108.0,15688333.96,6655774.04,2593,483,13780.070476,46261.093168,5.368530,8617.087543,2566.823772

In [33]:
seller_discount = product_analysis.groupby("Seller_ID")["Discount"].mean().reset_index(
    name="Average_Discount"
)

In [34]:
top_sellers_discount = seller_discount.sort_values(
    "Average_Discount",
    ascending=False
)

In [35]:
top_sellers_discount.head(10)

   Seller_ID  Average_Discount
29     S0030          0.116841
98     S0099          0.115937
32     S0033          0.115438
91     S0092          0.115202
74     S0075          0.115176
40     S0041          0.114772
20     S0021          0.114735
92     S0093          0.114576
49     S0050          0.114415
4      S0005          0.114299

In [36]:
product_analysis["Discount_Band"] = pd.cut(
    product_analysis["Discount"],
    bins=[-0.01, 0.05, 0.10, 0.15, 0.20, 1],
    labels=[
        "0–5%",
        "5–10%",
        "10–15%",
        "15–20%",
        "20%+"
    ]
)

In [37]:
discount_analysis = product_analysis.groupby(
    "Discount_Band",
    observed=True
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Order_Items=("Order_ID", "count")
).reset_index()

In [38]:
discount_analysis["Profit_Margin"] = (
    discount_analysis["Total_Profit"]
    / discount_analysis["Total_Sales"]
    * 100
)

In [39]:
discount_analysis

,Discount_Band,Total_Sales,Total_Profit,Total_Quantity,Order_Items,Profit_Margin
0,0–5%,727098874.0,2.635699e+08,86191,34423,36.249529
1,5–10%,481117906.0,1.538683e+08,58598,23507,31.981403
2,10–15%,453528570.0,1.285297e+08,58443,23363,28.339938
3,15–20%,230699099.0,5.272795e+07,31080,12431,22.855725
4,20%+,214850225.0,3.636800e+07,30401,12229,16.927142

In [40]:
product_discount_impact = product_analysis.groupby(
    ["Product_ID", "Product_Name", "Category", "Subcategory", "Brand"]
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Average_Discount=("Discount", "mean")
).reset_index()

In [41]:
product_discount_impact["Profit_Margin"] = (
    product_discount_impact["Total_Profit"]
    / product_discount_impact["Total_Sales"]
    * 100
)

In [42]:
product_discount_impact_filtered = product_discount_impact[
    product_discount_impact["Total_Sales"] >= 500000
]

In [43]:
product_discount_impact_filtered.sort_values(
    "Profit_Margin",
    ascending=True
).head(10)

,Product_ID,Product_Name,Category,Subcategory,Brand,Total_Sales,Total_Profit,Total_Quantity,Average_Discount,Profit_Margin
278,P0279,Everday Academic 09,Books,Academic,Everday,598411.0,72694.30,619,0.117769,12.147888
91,P0092,UrbanEdge Home Decor 02,Home & Kitchen,Home Decor,UrbanEdge,786086.0,96782.56,632,0.113594,12.311956
334,P0335,Zenith Office Furniture 05,Office Supplies,Office Furniture,Zenith,3137622.0,389028.06,694,0.114220,12.398819
39,P0040,BrightLife Audio 10,Electronics,Audio,BrightLife,4572708.0,572785.92,616,0.115217,12.526186
3,P0004,Aero Laptops 04,Electronics,Laptops,Aero,34505120.0,4342101.25,625,0.116308,12.583933
194,P0195,Zenith Skincare 15,Beauty & Personal Care,Skincare,Zenith,1015398.0,130643.22,637,0.112314,12.866208
144,P0145,Zenith Women 10,Fashion,Women,Zenith,2141412.0,275684.21,617,0.109922,12.873945
119,P0120,BrightLife Storage 15,Home & Kitchen,Storage,BrightLife,4208802.0,542597.64,609,0.108849,12.891974
112,P0113,HomeCraft Storage 08,Home & Kitchen,Storage,HomeCraft,1012928.0,131327.42,667,0.109358,12.965129
13,P0014,Aero Laptops 14,Electronics,Laptops,Aero,44597389.0,5809555.00,600,0.112314,13.026671

In [44]:
category_discount_impact = product_analysis.groupby(
    "Category"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Average_Discount=("Discount", "mean")
).reset_index()

In [45]:
category_discount_impact["Profit_Margin"] = (
    category_discount_impact["Total_Profit"]
    / category_discount_impact["Total_Sales"]
    * 100
)

In [46]:
category_discount_impact.sort_values(
    "Average_Discount",
    ascending=False
)

,Category,Total_Sales,Total_Profit,Total_Quantity,Average_Discount,Profit_Margin
2,Electronics,1.013188e+09,3.102759e+08,38225,0.119201,30.623715
3,Fashion,1.309160e+08,3.796829e+07,38169,0.117333,29.002034
1,Books,3.044337e+07,8.902038e+06,37540,0.109292,29.241298
4,Home & Kitchen,3.228456e+08,9.169219e+07,37262,0.108701,28.401248
0,Beauty & Personal Care,6.638252e+07,1.960781e+07,37919,0.107864,29.537613
6,Sports & Fitness,2.603527e+08,8.220308e+07,37901,0.107213,31.573742
5,Office Supplies,2.831664e+08,8.441458e+07,37697,0.107160,29.810948

In [47]:
orders_clean["Year_Month"] = orders_clean["Order_Date"].dt.to_period("M")

In [48]:
monthly_orders = orders_clean.groupby(
    "Year_Month"
).agg(
    Total_Orders=("Order_ID", "nunique")
).reset_index()

In [49]:
monthly_financials = product_analysis.merge(
    orders_clean[["Order_ID", "Order_Date"]],
    on="Order_ID",
    how="left"
)

In [50]:
monthly_financials["Year_Month"] = (
    monthly_financials["Order_Date"].dt.to_period("M")
)

In [51]:
monthly_summary = monthly_financials.groupby(
    "Year_Month"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

In [52]:
monthly_summary

   Year_Month  Total_Sales  Total_Profit  Total_Quantity
0     2024-01   66127927.0   20375356.58            8162
1     2024-02   64307142.0   19625723.12            7775
2     2024-03   70190239.0   21144411.95            8736
3     2024-04   68988271.0   21104991.21            8116
4     2024-05   72221987.0   22605786.19            8793
5     2024-06   73744181.0   22162507.77            8872
6     2024-07   68292283.0   20992597.68            8282
7     2024-08   63901205.0   19472449.21            8187
8     2024-09   70328808.0   21619822.53            8373
9     2024-10   64004301.0   18475977.49            8766
10    2024-11   58603287.0   16331854.78            8007
11    2024-12   63912885.0   18063547.36            8418
12    2025-01   75618176.0   23015991.52            9153
13    2025-02   61435109.0   18514079.84            7520
14    2025-03   72050083.0   21707939.40            8658
15    2025-04   62954616.0   19282504.90            8071
16    2025-05   69891644.0   21125390.71            8702
17    2025-06   68738708.0   21047496.17            8574
18    2025-07   65930419.0   20615092.63            8608
19    2025-08   68619298.0   21114823.52            8493
20    2025-09   68567200.0   20873801.84            8608
21    2025-10   62217395.0   17965895.14            8452
22    2025-11   68418337.0   19339845.88            8587
23    2025-12   68616059.0   19472353.93            8951
24    2026-01   66675360.0   19933086.39            8350
25    2026-02   59296653.0   18122784.43            7542
26    2026-03   65656405.0   20142785.81            8305
27    2026-04   64532484.0   19656432.40            8503
28    2026-05   65643916.0   19838476.50            8489
29    2026-06   68174494.0   21128093.06            8318
30    2026-07   70503752.0   21524322.74            8735
31    2026-08   29132050.0    8667620.47            3607

In [53]:
monthly_summary = monthly_summary.merge(
    monthly_orders,
    on="Year_Month",
    how="left"
)

monthly_summary["Profit_Margin"] = (
    monthly_summary["Total_Profit"]
    / monthly_summary["Total_Sales"]
    * 100
)

monthly_summary

,Year_Month,Total_Sales,Total_Profit,Total_Quantity,Total_Orders,Profit_Margin
0,2024-01,66127927.0,20375356.58,8162,1599,30.812030
1,2024-02,64307142.0,19625723.12,7775,1453,30.518730
2,2024-03,70190239.0,21144411.95,8736,1639,30.124434
3,2024-04,68988271.0,21104991.21,8116,1537,30.592144
4,2024-05,72221987.0,22605786.19,8793,1635,31.300421
5,2024-06,73744181.0,22162507.77,8872,1679,30.053229
6,2024-07,68292283.0,20992597.68,8282,1558,30.739341
7,2024-08,63901205.0,19472449.21,8187,1544,30.472742
8,2024-09,70328808.0,21619822.53,8373,1575,30.741062
9,2024-10,64004301.0,18475977.49,8766,1644,28.866775
10,2024-11,58603287.0,16331854.78,8007,1528,27.868496
11,2024-12,63912885.0,18063547.36,8418,1641,28.262763
12,2025-01,75618176.0,23015991.52,9153,1697,30.437115
13,2025-02,61435109.0,18514079.84,7520,1442,30.135992
14,2025-03,72050083.0,21707939.40,8658,1570,30.128958
15,2025-04,62954616.0,19282504.90,8071,1535,30.629215
16,2025-05,69891644.0,21125390.71,8702,1613,30.225918
17,2025-06,68738708.0,21047496.17,8574,1598,30.619569
18,2025-07,65930419.0,20615092.63,8608,1648,31.267953
19,2025-08,68619298.0,21114823.52,8493,1649,30.770970
20,2025-09,68567200.0,20873801.84,8608,1606,30.442838
21,2025-10,62217395.0,17965895.14,8452,1604,28.876000
22,2025-11,68418337.0,19339845.88,8587,1620,28.267051
23,2025-12,68616059.0,19472353.93,8951,1680,28.378712
24,2026-01,66675360.0,19933086.39,8350,1598,29.895731
25,2026-02,59296653.0,18122784.43,7542,1432,30.562913
26,2026-03,65656405.0,20142785.81,8305,1564,30.679087
27,2026-04,64532484.0,19656432.40,8503,1580,30.459749
28,2026-05,65643916.0,19838476.50,8489,1612,30.221348
29,2026-06,68174494.0,21128093.06,8318,1552,30.991199
30,2026-07,70503752.0,21524322.74,8735,1684,30.529329
31,2026-08,29132050.0,8667620.47,3607,684,29.752868

In [54]:
monthly_summary["Month"] = monthly_summary["Year_Month"].dt.month

In [55]:
seasonal_summary = monthly_summary[
    ~(
        (monthly_summary["Year_Month"] == pd.Period("2026-08"))
    )
]

In [56]:
seasonal_summary = seasonal_summary.groupby(
    "Month"
).agg(
    Avg_Sales=("Total_Sales", "mean"),
    Avg_Profit=("Total_Profit", "mean"),
    Avg_Orders=("Total_Orders", "mean"),
    Avg_Quantity=("Total_Quantity", "mean"),
    Avg_Profit_Margin=("Profit_Margin", "mean")
).reset_index()

In [57]:
seasonal_summary

,Month,Avg_Sales,Avg_Profit,Avg_Orders,Avg_Quantity,Avg_Profit_Margin
0,1,6.947382e+07,2.110814e+07,1631.333333,8555.000000,30.381625
1,2,6.167963e+07,1.875420e+07,1442.333333,7612.333333,30.405879
2,3,6.929891e+07,2.099838e+07,1591.000000,8566.333333,30.310826
3,4,6.549179e+07,2.001464e+07,1550.666667,8230.000000,30.560369
4,5,6.925252e+07,2.118988e+07,1620.000000,8661.333333,30.582562
5,6,7.021913e+07,2.144603e+07,1609.666667,8588.000000,30.554666
6,7,6.824215e+07,2.104400e+07,1630.000000,8541.666667,30.845541
7,8,6.626025e+07,2.029364e+07,1596.500000,8340.000000,30.621856
8,9,6.944800e+07,2.124681e+07,1590.500000,8490.500000,30.591950
9,10,6.311085e+07,1.822094e+07,1624.000000,8609.000000,28.871388
10,11,6.351081e+07,1.783585e+07,1574.000000,8297.000000,28.067773
11,12,6.626447e+07,1.876795e+07,1660.500000,8684.500000,28.320738

In [58]:
segment_analysis = product_analysis.merge(
    orders_clean[["Order_ID", "Customer_ID"]],
    on="Order_ID",
    how="left"
)

In [59]:
segment_analysis = segment_analysis.merge(
    customers_clean[["Customer_ID", "Customer_Segment"]],
    on="Customer_ID",
    how="left"
)

In [60]:
segment_summary = segment_analysis.groupby(
    "Customer_Segment"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Total_Order_Items=("Order_ID", "count"),
    Total_Orders=("Order_ID", "nunique"),
    Total_Customers=("Customer_ID", "nunique")
).reset_index()

In [61]:
segment_summary["Profit_Margin"] = (
    segment_summary["Total_Profit"]
    / segment_summary["Total_Sales"]
    * 100
)

segment_summary["Average_Order_Value"] = (
    segment_summary["Total_Sales"]
    / segment_summary["Total_Orders"]
)

In [62]:
segment_summary.sort_values(
    "Total_Profit",
    ascending=False
)

,Customer_Segment,Total_Sales,Total_Profit,Total_Quantity,Total_Order_Items,Total_Orders,Total_Customers,Profit_Margin,Average_Order_Value
2,Small Business,717550272.0,2.158197e+08,90693,36279,17165,687,30.077290,41803.103525
0,Consumer,708749589.0,2.135621e+08,88452,35403,16732,670,30.132238,42358.928341
1,Corporate,680994813.0,2.056821e+08,85568,34271,16103,643,30.203175,42289.934360

In [63]:
region_analysis = product_analysis.merge(
    orders_clean[["Order_ID", "Customer_ID"]],
    on="Order_ID",
    how="left"
)

In [64]:
region_analysis = region_analysis.merge(
    customers_clean[["Customer_ID", "Region"]],
    on="Customer_ID",
    how="left"
)

In [65]:
region_summary = region_analysis.groupby(
    "Region"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Total_Order_Items=("Order_ID", "count"),
    Total_Orders=("Order_ID", "nunique"),
    Total_Customers=("Customer_ID", "nunique")
).reset_index()

In [66]:
region_summary["Profit_Margin"] = (
    region_summary["Total_Profit"]
    / region_summary["Total_Sales"]
    * 100
)

region_summary["Average_Order_Value"] = (
    region_summary["Total_Sales"]
    / region_summary["Total_Orders"]
)

In [67]:
region_summary.sort_values(
    "Total_Sales",
    ascending=False
)

,Region,Total_Sales,Total_Profit,Total_Quantity,Total_Order_Items,Total_Orders,Total_Customers,Profit_Margin,Average_Order_Value
1,North,568672727.0,1.714842e+08,72203,28923,13704,547,30.155161,41496.842309
3,West,530143416.0,1.596064e+08,67632,27267,12842,517,30.106264,41281.997820
2,South,529346162.0,1.592396e+08,65265,25953,12255,490,30.082315,43194.301265
0,East,479132369.0,1.447337e+08,59613,23810,11199,446,30.207458,42783.495759

In [68]:
status_financial_impact = product_analysis.groupby(
    "Order_Status"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Cost=("Cost", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Order_Items=("Order_ID", "count"),
    Total_Orders=("Order_ID", "nunique")
).reset_index()

In [75]:
status_financial_impact["Sales_Share"] = (
    status_financial_impact["Total_Sales"]
    / total_sales * 100
)

status_financial_impact["Profit_Share"] = (
    status_financial_impact["Total_Profit"]
    / total_profit * 100
)

status_financial_impact

NameError: name 'total_sales' is not defined

In [76]:
status_financial_impact["Sales_Share"] = (
    status_financial_impact["Total_Sales"]
    / status_financial_impact["Total_Sales"].sum()
    * 100
)

status_financial_impact["Profit_Share"] = (
    status_financial_impact["Total_Profit"]
    / status_financial_impact["Total_Profit"].sum()
    * 100
)

status_financial_impact

,Order_Status,Total_Sales,Total_Cost,Total_Profit,Total_Quantity,Order_Items,Total_Orders,Sales_Share,Profit_Share
0,Cancelled,1.064105e+08,7.407887e+07,3.233166e+07,13095,5286,2512,5.049627,5.091088
1,Completed,1.808453e+09,1.263440e+09,5.450131e+08,227643,91071,42954,85.818692,85.820205
2,Pending,8.706792e+07,6.115956e+07,2.590836e+07,10948,4366,2047,4.131739,4.079646
3,Returned,1.053635e+08,7.355276e+07,3.181073e+07,13027,5230,2487,4.999941,5.009061

In [77]:
customer_order_frequency = orders_clean.groupby(
    "Customer_ID"
).agg(
    Total_Orders=("Order_ID", "nunique")
).reset_index()

customer_order_frequency["Customer_Type"] = np.where(
    customer_order_frequency["Total_Orders"] > 1,
    "Repeat Customer",
    "One-Time Customer"
)

customer_frequency_summary = customer_order_frequency.groupby(
    "Customer_Type"
).agg(
    Customers=("Customer_ID", "count")
).reset_index()

customer_frequency_summary["Percentage"] = (
    customer_frequency_summary["Customers"]
    / customer_frequency_summary["Customers"].sum()
    * 100
)

customer_frequency_summary

     Customer_Type  Customers  Percentage
0  Repeat Customer       2000       100.0

In [78]:
customer_order_frequency["Total_Orders"].describe()

count    2000.000000
mean       25.000000
std         4.977589
min        12.000000
25%        22.000000
50%        25.000000
75%        28.000000
max        44.000000
Name: Total_Orders, dtype: float64

In [79]:
customer_order_frequency.sort_values(
    "Total_Orders",
    ascending=False
).head(10)

     Customer_ID  Total_Orders    Customer_Type
1006      C01007            44  Repeat Customer
788       C00789            42  Repeat Customer
145       C00146            42  Repeat Customer
1215      C01216            41  Repeat Customer
657       C00658            40  Repeat Customer
142       C00143            39  Repeat Customer
311       C00312            38  Repeat Customer
492       C00493            38  Repeat Customer
1619      C01620            38  Repeat Customer
299       C00300            38  Repeat Customer

In [80]:
customer_order_frequency["Frequency_Rank"] = (
    customer_order_frequency["Total_Orders"]
    .rank(method="first", ascending=False)
)

customer_order_frequency["Customer_Group"] = np.where(
    customer_order_frequency["Frequency_Rank"] <= 500,
    "Top 25% Customers",
    "Other Customers"
)

In [81]:
customer_value_analysis = product_analysis.merge(
    orders_clean[["Order_ID", "Customer_ID"]],
    on="Order_ID",
    how="left"
).merge(
    customer_order_frequency[
        ["Customer_ID", "Customer_Group"]
    ],
    on="Customer_ID",
    how="left"
)

In [82]:
customer_group_summary = customer_value_analysis.groupby(
    "Customer_Group"
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Total_Order_Items=("Order_ID", "count"),
    Total_Orders=("Order_ID", "nunique"),
    Total_Customers=("Customer_ID", "nunique")
).reset_index()

customer_group_summary["Profit_Margin"] = (
    customer_group_summary["Total_Profit"]
    / customer_group_summary["Total_Sales"]
    * 100
)

customer_group_summary["Sales_Share"] = (
    customer_group_summary["Total_Sales"]
    / customer_group_summary["Total_Sales"].sum()
    * 100
)

customer_group_summary

,Customer_Group,Total_Sales,Total_Profit,Total_Quantity,Total_Order_Items,Total_Orders,Total_Customers,Profit_Margin,Sales_Share
0,Other Customers,1.443600e+09,4.355176e+08,181299,72530,34286,1500,30.168845,68.504918
1,Top 25% Customers,6.636942e+08,1.995463e+08,83414,33423,15714,500,30.065994,31.495082

In [83]:
print(customers_clean.shape)
print(products_clean.shape)
print(orders_clean.shape)
print(sellers_clean.shape)
print(order_items_clean.shape)

(2000, 9)
(420, 7)
(50000, 8)
(100, 4)
(105953, 9)

In [84]:
print(
    customers_clean.columns.tolist(),
    products_clean.columns.tolist(),
    orders_clean.columns.tolist(),
    sellers_clean.columns.tolist(),
    order_items_clean.columns.tolist(),
    sep="\n\n"
)

['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'Customer_Segment', 'City', 'State', 'Region', 'Signup_Date']

['Product_ID', 'Product_Name', 'Category', 'Subcategory', 'Brand', 'Unit_Cost', 'Unit_Price']

['Order_ID', 'Order_Date', 'Customer_ID', 'Seller_ID', 'Order_Status', 'Payment_Method', 'Shipping_Mode', 'Year_Month']

['Seller_ID', 'Seller_Name', 'Seller_Type', 'Seller_Region']

['Order_ID', 'Product_ID', 'Seller_ID', 'Quantity', 'Discount', 'Sales', 'Cost', 'Profit', 'Order_Status']

In [85]:
customers_clean.to_csv("customers_clean.csv", index=False)
products_clean.to_csv("products_clean.csv", index=False)
orders_clean.to_csv("orders_clean.csv", index=False)
sellers_clean.to_csv("sellers_clean.csv", index=False)
order_items_clean.to_csv("order_items_clean.csv", index=False)

print("All cleaned datasets exported successfully.")

All cleaned datasets exported successfully.

In [86]:
import os

[f for f in os.listdir() if "_clean.csv" in f]

['sellers_clean.csv',
 'orders_clean.csv',
 'customers_clean.csv',
 'order_items_clean.csv',
 'products_clean.csv']